from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_layout = QtWidgets.QHBoxLayout()
        self.label_layout.setObjectName("label_layout")
        self.left_label = QtWidgets.QLabel(self.centralwidget)
        self.left_label.setMinimumSize(QtCore.QSize(640, 480))
        self.left_label.setObjectName("left_label")
        self.left_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_layout.addWidget(self.left_label)
        self.right_label = QtWidgets.QLabel(self.centralwidget)
        self.right_label.setMinimumSize(QtCore.QSize(640, 480))
        self.right_label.setObjectName("right_label")
        self.right_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_layout.addWidget(self.right_label)
        self.verticalLayout.addLayout(self.label_layout)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.control_layout = QtWidgets.QHBoxLayout()
        self.control_layout.setObjectName("control_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.control_layout.addItem(spacerItem)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.control_layout.addWidget(self.open_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.control_layout.addItem(spacerItem1)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.control_layout.addWidget(self.stop_button)
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        self.prev_button.setObjectName("prev_button")
        self.control_layout.addWidget(self.prev_button)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setObjectName("play_button")
        self.control_layout.addWidget(self.play_button)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setObjectName("next_button")
        self.control_layout.addWidget(self.next_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.control_layout.addItem(spacerItem2)
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setObjectName("quit_button")
        self.control_layout.addWidget(self.quit_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.control_layout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.control_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1294, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.prev_button.setText(_translate("MainWindow", "Previous"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
